version: '3'
services:
  mosquitto:
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    command: ['mosquitto', '-c', '/mosquitto/config/mosquitto.conf']
    ports:
      - '1881:1881'
      - '1883:1883'
      - '9001:9001'

  postgres_db:
    image: postgres
    environment:
      POSTGRES_DB: mosquitto
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    ports:
      - '5432:5432'